apps/productos/urls.py
from django.urls import path
from apps.productos.views import index, listado, categorias, ViewProducto, home, nuevoRegistro, editarRegistro, eliminarRegistro, prebunta, nuevoRegistroC, editarRegistroC, eliminarRegistroC, prebuntaC, listadoC, comprar, prueba, Ventas, ventaFormulario, ErrorCantidad

app_name = 'productos'
urlpatterns = [
	path('', index),
	path('index', index),
	path('producto/index', index),
	path('categorias', categorias),

	path('idk', ViewProducto.as_view()),
	path('home', home, name="home"),

	path('prueba', prueba, name="prueba"),

	path('ErrorCantidad', ErrorCantidad, name="ErrorCantidad"),
	path('ventaProducto/<idProducto>', ventaFormulario, name="ventasFormulario"),

	path('listado', listado, name="infoproductos"),
	path('prebunta/<idProducto>', prebunta, name="prebunta"),
	path('nuevoRegistro', nuevoRegistro, name="nuevoRegistro"),
	path('editarRegistro/<idProducto>', editarRegistro, name="editarRegistro"),
	path('eliminarRegistro/<idProducto>', eliminarRegistro, name="eliminarRegistro"),

	path('comprar', comprar, name="comprar"),

	path('listadoC', categorias, name="infocategorias"),
	path('prebuntaC/<idCategoria>', prebuntaC, name="prebuntaC"),
	path('nuevoRegistroC', nuevoRegistroC, name="nuevoRegistroC"),
	path('editarRegistroC/<idCategoria>', editarRegistroC, name="editarRegistroC"),
	path('eliminarRegistroC/<idCategoria>', eliminarRegistroC, name="eliminarRegistroC"),
]

proyectoTienda/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('admin/', admin.site.urls),
	path('productos/', include('apps.productos.urls')),
	path('', include('apps.productos.urls')),
   # path('especialC/', include('apps.productos.urls')),
]

apps/productos/models.py
from django.db import models

class Categoria(models.Model):
	NombreCat = models.CharField(max_length=30)
	FechaCreacion = models.DateField(default = '2000-01-01')

	def __str__(self):
		return '{}'.format(self.NombreCat)

class Producto(models.Model):
	Nombre = models.CharField(max_length=30)
	Descripcion = models.CharField(max_length=30)
	Costo = models.IntegerField(default = 0)
	Disponible = models.BooleanField(default = 0)
	NumExistencia = models.IntegerField(default = 1)
	Categoria = models.ForeignKey(Categoria, null=True, blank = True, on_delete = models.CASCADE)
	# wtf is this
	def __str__(self):
		return '{}'.format(self.id)

apps/productos/forms.py
from django import forms
from apps.productos.models import Producto, Categoria

class ProductoForm(forms.ModelForm):
	class Meta:
		model = Producto

		fields = [
			'Nombre',
			'Descripcion',
			'Costo',
			'Disponible',
			'NumExistencia',
			'Categoria',
		]

		labels = {
			'Nombre' : 'Nombre',
			'Descripcion' : 'Descripcion',
			'Costo' : 'Costo',
			'Disponible' : 'Disponibilidad',
			'NumExistencia' : 'Cantidad en Existencia',
			'Categoria' : 'Categoria',
		}

		widgets = {
			'Nombre' : forms.TextInput(attrs ={'class':'form-control'}),
			'Descripcion' : forms.TextInput(attrs ={'class':'form-control'}),
			'Costo' : forms.TextInput(attrs ={'class':'form-control'}),
			'Disponible' : forms.TextInput(attrs ={'class':'form-control'}),
			'NumExistencia' : forms.TextInput(attrs ={'class':'form-control'}),
			'Categoria' : forms.TextInput(attrs ={'class':'form-control'}),
		}

class CategoriaForm(forms.ModelForm):
	class Meta:
		model = Categoria

		fields = [
			'NombreCat',
			'FechaCreacion',
		]

		labels = {
			'NombreCat' : 'Nombre Categoria',
			'FechaCreacion' : 'Fecha de Creacion',
		}

		widgets = {
			'NombreCat' : forms.TextInput(attrs ={'class':'form-control'}),
			'FechaCreacion' : forms.TextInput(attrs ={'class':'form-control'}),
		}

class VentasForm(forms.ModelForm):
	class Meta:
		model = Producto

		fields = [
			'Nombre',
			'Costo',
			'NumExistencia',
		]

		labels = {
			'Nombre' : 'Nombre',
			'Costo' : 'Costo',
			'NumExistencia' : 'Cantidad',
		}

		widgets = {
			'Nombre' : forms.TextInput(attrs ={'class':'form-control', 'readonly':'readonly'}),
			'Costo' : forms.TextInput(attrs ={'class':'form-control', 'readonly':'readonly'}),
			'NumExistencia' : forms.NumberInput(attrs ={'class':'form-control', 'min':'0'}),
		}

apps/productos/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic import ListView
from apps.productos.models import Producto, Categoria
from apps.productos.forms import ProductoForm, CategoriaForm, VentasForm

def prueba(request):
	return HttpResponse("le")

def home(request):
	return render(request, 'home/index.html')

def index(request):
	return HttpResponse("Esta es la respuesta")

def listado(request):
	contexto = {
		'productos': Producto.objects.all()
	}
	return render(request, 'productos/infoproductos.html', contexto)

def comprar(request):
	contexto = {
		'productos': Producto.objects.all()
	}
	return render(request, 'productos/infoVentas.html', contexto)

def listadoC(request):
	contexto = {
		'categorias': Categoria.objects.all()
	}
	return render(request, 'productosCategoria/infocategorias.html', contexto)

def categorias(request):
	contexto = {
		'Categorias': Categoria.objects.all()
	}
	return render(request, 'productosCategoria/paginaCategoria.html', contexto)

def nuevoRegistro(request):
	if request.method == 'POST':
		form = ProductoForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('productos:infoproductos')
	else:
		form = ProductoForm()
	return render(request, 'productos/productoFormulario.html', {'form' : form})

def editarRegistro(request, idProducto):
	producto = Producto.objects.get(id = idProducto)
	if (request.method == 'GET'):
		form = ProductoForm(instance = producto)
	else:
		form = ProductoForm(request.POST, instance=producto)
		if form.is_valid():
			form.save()
		return redirect('productos:infoproductos')
	return render(request, 'productos/productoFormulario.html', {'form' : form})

def eliminarRegistro(request, idProducto):
	producto = Producto.objects.get(id = idProducto)
	if (request.method == 'GET'):
		form = ProductoForm(instance = producto)
	else:
		form = ProductoForm(request.POST, instance=producto)
		if form.is_valid():
			producto.delete()
		return redirect('productos:infoproductos')
	return render(request, 'productos/prebunta.html', {'form' : form})

class ViewProducto(ListView):
	model = Producto
	queryset = Producto.objects.all()
	templeate_name = 'productos/infoproductos.html'

class Ventas(ListView):
	model = Producto
	queryset = Producto.objects.all()
	templeate_name = 'productos/pagVentas.html'

def ventaFormulario(request,idProducto):
	producto = Producto.objects.get(id = idProducto)
	cant = producto.NumExistencia
	producto.NumExistencia = 0
	if (request.method == "GET"):
		form = VentasForm(instance = producto)
	else:
		form = VentasForm(request.POST, instance=producto)
		if form.is_valid():
			Costo = producto.NumExistencia
			producto.NumExistencia = cant - producto.NumExistencia
			if producto.NumExistencia < 0:
				return redirect('productos:ErrorCantidad')
			form.save()
		Costo = float(Costo) * producto.Costo
		contexto = {'Costo':Costo}
		return render(request, 'productos/pago.html', contexto)
		return redirect('productos:uarida')
	return render(request, 'productos/ventaFormulario.html', {'form' : form})

def ErrorCantidad(request):
	return render(request, 'productos/problemo.html')

def prebunta(request, idProducto):
 	return render(request, 'productos/prebunta.html')

def nuevoRegistroC(request):
	if request.method == 'POST':
		form = CategoriaForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('productosCategoria:infocategorias')
	else:
		form = CategoriaForm()
	return render(request, 'productosCategoria/categoriaFormulario.html', {'form' : form})

def editarRegistroC(request, idCategoria):
	categoria = Categoria.objects.get(id = idCategoria)
	if (request.method == 'GET'):
		form = CategoriaForm(instance = categoria)
	else:
		form = CategoriaForm(request.POST, instance = categoria)
		if form.is_valid():
			form.save()
		return redirect('productos:infocategorias')
	return render(request, 'productosCategoria/categoriaFormulario.html', {'form' : form})

def eliminarRegistroC(request, idCategoria):
	categoria = Categoria.objects.get(id = idCategoria)
	if (request.method == 'GET'):
		form = CategoriaForm(instance = categoria)
	else:
		form = CategoriaForm(request.POST, instance = categoria)
		if form.is_valid():
			categoria.delete()
		return redirect('productos:infocategorias')
	return render(request, 'productosCategoria/prebuntaC.html', {'form' : form})

def prebuntaC(request, idCategoria):
	return render(request, 'productosCategoria/prebuntaC.html')

templates/base/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<!--Estilo para TODAS las páginas que hereden de esta plantilla-->
	{% include 'base/nav.html' %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
	<!-- Bloque para incrustar otros css diferentes por página -->
	<script type="text/javascript" src="{% static 'js/funciones.js' %}"></script>
	{% block extracss %}
	
	{% endblock %}

	<title>{%block title %}Proyecto{% endblock %}</title>
</head>
<body>
	<header>
		{%block header %}

		<a href="{% url 'productos:home' %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Tienda</a>

		{% endblock %}
	</header>
	<div>
		{%block content %}
		Contenido de la página
		{% endblock %}
	</div>

	<footer>
		{%block footer %}

		{% endblock %}
	</footer>
	<scripts type="text/javascripts" src="{% static 'js/bootstrap.js' %}"></script>
		<scripts type="text/javascripts" src="{% static 'jquery-3.3.1.min.js' %}"></script>	
		</body>
		<!-- <div class="form-group row">
			<label for="example-text-input" class="col-2 col-form-label">Ingresa tu nombre</label>
			<div class="col-10">
				<input class="form-control" type="text" value="" id="Nombre">
			</div>
		</div>

		<td><button id="boton" type="button" onClick=OK() class="btn btn-success">OK</button></td>

		<script type="text/javascript">
			function OK(){
				alert(document.getElementById("Nombre").value);
			}
		</script> -->
		</html>

templates/base/informacionAdicional.html
<ol>
	<li>Opcion 1</li>
	<li>Opcion 2</li>
	<li>Opcion 3</li>
	<li>Opcion 4</li>
	<li>Opcion 5</li>
</ol>

templates/base/nav.html
<!-- <nav class="navbar navbar-dark bg-dark mb-3">
	<a class="navbar-brand">Tea-Tienda</a>
	<ul class="navbar.nav mr-auto">
		<li class="nav-item active">
			<a class="nav-link" href="{% url 'productos:infoproductos' %}">Productos</a>
		</li>
	</ul>
</nav> -->

templates/home/index.html
{% extends 'base/index.html' %}

{% block title %}
Home
{% endblock %}

{% block content %}
<nav class="navbar navbar-expand-sm navbar-light bg-light">
  <a class="navbar-brand" href="categorias">Categorias</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="listado">Productos <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="comprar">Comprar <span class="sr-only">(current)</span></a>
      </li>    
    </ul>    
  </div>
</nav>
<div>
  <img src="https://www.xactplacements.co.uk/wp-content/uploads/2017/11/welcome-images-25.png" width="600" height="250">
</div>
{% endblock %}

templates/productos/index.html
{% extends 'base/index.html' %}

{% block title %}
Productos
{% endblock %}

{% block content %}
Esta es la página para Productos wtf
{% include 'base/informacionAdicional.html' %}
{% endblock %}

templates/productos/infoVentas.html
{% extends 'base/index.html' %}
{% load staticfiles %}

{% block extracss %}
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">

{% endblock %}

{% block header %}
<a href="home" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Tienda</a>
{% endblock %}

{% block content %}
<divc class="container"></div>
<table class="table">
	<thead>
		<tr>
			<th scope="col">ID</th>
			<th scope="col">Nombre</th>
			<th scope="col">Cantidad disponible</th>
			<th scope="col">Costo</th>
			<th scope="col"></th>
		</tr>
	</thead>
	<tbody>
		{% for producto in productos %}
		<tr>
			<th scope="row">{{producto.id}}</th>
			<td>{{producto.Nombre}}</td>
			<td>{{producto.NumExistencia}}</td>
			<td>{{producto.Costo}}</td>
			<td>
				<a href="{% url 'productos:ventasFormulario' producto.id %}" class="btn btn-success">
					Comprar
				</a>
			</td>
		</tr>
		{% empty %}
		<tr>
			<td colspan="6">No hay elementos</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
{% endblock %}

templates/productos/infoproductos.html
{% extends 'base/index.html' %}
{% load staticfiles %}

{% block extracss %}
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
{% endblock %}

{% block header %}
<a href="home" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Tienda</a>
{% endblock %}

{% block content %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Nombre</th>
      <th scope="col">Categoria</th>
      <th scope="col">Descripcion</th>
      <th scope="col">NumExistencia</th>
      <th scope="col">Costo</th>
      <th scope="col">Acciones</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      {% for producto in productos %}
      <th scope="row">{{producto.id}}</th>
      <td>{{producto.Nombre}}</td>
      <td>{{producto.Categoria}}</td>
      <td>{{producto.Descripcion}}</td>
      <td>{{producto.NumExistencia}}</td>
      <td>{{producto.Costo}}</td>
      <td>
        <a href="{% url 'productos:editarRegistro' producto.id %}" class="btn mb-3 btn-info">Editar</a>
        <a href="{% url 'productos:eliminarRegistro' producto.id %}" class="btn mb-3 btn-danger">Borrar</a>
      </td>
    </tr>
    {% empty %}
    <tr>
    	<td>No hay Producto</td>

    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}

templates/productos/pagVentas.html
{% extends 'base/index.html' %}
{% load staticfiles %}

{% block title %}
Ventas
{% endblock %}

{% block header %}
Ventas
{% endblock %}

{% block content %}
<div class="container">
	{% include 'productos/infoVentas.html' %}
</div>
{% endblock %}

{% block footer %}
{% endblock %}

templates/productos/paginaEspecial.html
{% extends 'base/index.html' %}
{% load staticfiles %}

{% block extracss %}

{% endblock %}

{% block content %}

<divc class ="container">
  <a href="{% url 'productos:nuevoRegistro' %}" class="btn mb-3">Nuevo registro</a>

{% include 'informacion/infoproductos.html' %}
</divc>
{% endblock %}

templates/productos/pago.html
{% extends 'base/index.html' %}

{% block title %}
Pago
{% endblock %}

{% block content %}

<ol>
		<h3 class="text-center">Total : ${{Costo}}</h3>
		<a href="{% url 'productos:comprar' %}" class="btn mb-3 btn-primary btn-lg btn-block">
					Regresar a la Tienda
				</a>
</ol>


{% endblock %}

templates/productos/prebunta.html
{% extends 'base/index.html' %}
{% load staticfiles %}

{% block extracss %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
{% endblock %}

{% block content %}

<div class="container">
	<div class="row justify-content-md-center">
		<div class="col-8">
			<h1>¿Esta seguro de eliminar el Producto?</h1>
			<form method="post">
				{% csrf_token %}
				{{ form.as_p }}

				<button type="submit" class="btn btn-danger btn-lg btn-block">ELIMINAR</button>
				<a class="btn btn-warning btn-lg btn-block" href="{% url 'productos:infoproductos' %}" class="btn mb-3" >CANCELAR</a>
			</form>
		</div>
	</div>
</div>

{% endblock %}

templates/productos/problemo.html
{% extends 'base/index.html' %}

{% block title %}

{% endblock %}

{% block content %}
<ol>
	<h2 class="text-center">No puedes comprar más de los que hay en existencia</h2>
	<div class="container-center">
		<a href="{% url 'productos:comprar' %}" class="btn m-3 btn-warning btn-lg btn-block">OK</a>
	</div>
</ol>

{% endblock %}

templates/productos/productoFormulario.html
{% extends 'base/index.html' %}
{% load staticfiles %}

{% block title %}
	Registro de Producto
{% endblock %}

{% block extracss %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
{% endblock %}

{% block content %}

<div class="container">
	<div class="row justify-content-md-center">
		<div class="col-8">
			<h1>Modificación de Producto</h1>
			<form method="post">
				{% csrf_token %}
				{{ form.as_p }}
				<button type="submit" class="btn btn-success btn-lg btn-block">Enviar</button>
				<a type="submit" class="btn btn-warning btn-lg btn-block" href="{% url 'productos:infoproductos' %}" class="btn mb-3">Cancelar</a>
			</form>
		</div>
	</div>
</div>

{% endblock %}

templates/productos/ventaFormulario.html
{% extends 'base/index.html' %}
{% load staticfiles %}

{% block title %}
	Registro
{% endblock %}

{% block extracss %}

{% endblock %}

{% block content %}
<divc class="container">
	<div class = "row justify-content-md-center">
		<div class = "col-8">
			<h1>Comprar</h1>
			<form method="post">
				{% csrf_token %}
				{{ form.as_p}}
				<button type="submit" class="btn btn-success btn-lg btn-block">Comprar</button>
				<a class="btn btn-warning btn-lg btn-block" href="{% url 'productos:comprar' %}" class="btn mb-3" >Cancelar</a>
			</form>
		</div>
	</div>
</div>
{% endblock %}

templates/productosCategoria/categoriaFormulario.html
{% extends 'base/index.html' %}
{% load staticfiles %}

{% block extracss %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
{% endblock %}

{% block content %}

<div class="container">
	<div class="row justify-content-md-center">
		<div class="col-8">
			<h1>Edición Categoria</h1>
			<form method="post">
				{% csrf_token %}
				{{ form.as_p }}
				<button type="submit" class="btn btn-success btn-lg btn-block">Enviar</button>
				<a type="submit" class="btn btn-warning btn-lg btn-block" href="{% url 'productos:infocategorias' %}" class="btn mb-3">Cancelar</a>
			</form>
		</div>
	</div>
</div>

{% endblock %}

templates/productosCategoria/index.html
{% extends 'base/index.html' %}

{% block title %}
Categorias
{% endblock %}

{% block content %}
Esta es la página para Categorias
{% include 'base/informacionAdicional.html' %}
{% endblock %}

templates/productosCategoria/infocategorias.html
{% extends 'base/index.html' %}
{% load staticfiles %}

{% block extracss %}
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
{% endblock %}

{% block header %}
<a href="home" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Tienda</a>
{% endblock %}

{% block content %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">Nombre Categoria</th>
      <th scope="col">Fecha Creación</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      {% for categoria in Categorias %}
      <td>{{categoria.NombreCat}}</td>
      <td>{{categoria.FechaCreacion}}</td>
      <td>
        <a href="{% url 'productos:editarRegistroC' categoria.id %}" class="btn mb-3 btn-info">Editar</a>
        <a href="{% url 'productos:eliminarRegistroC' categoria.id %}" class="btn mb-3 btn-danger">Borrar</a>
      </td>
    </tr>
    {% empty %}
    <tr>
      <td>No hay Categoria</td>

    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}

templates/productosCategoria/infrocategorias.html
{% extends 'base/index.html' %}
{% load staticfiles %}

{% block extracss %}
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
{%  endblock%}

{% block content %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">Nombre Categoria</th>
      <th scope="col">Fecha Creación</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>{{categoria.NombreCat}}</td>
      <td>{{categoria.FechaCreacion}}</td>
      <td>
                  <a href="{% url 'productosCategoria:editarRegistroC' categoria.id %}" class="btn mb-3">Editar</a>
                  <a href="{% url 'productosCategoria:prebuntaC' categoria.id %}" class="btn mb-3">Borrar</a>
      </td>
    </tr>
    	{% empty %}
    <tr>
    	<td>No hay Categoria</td>

    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}

templates/productosCategoria/paginaCategoria.html
{% extends 'base/index.html' %}
{% load staticfiles %}

{% block extracss %}
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
{% endblock %}

{% block header %}
<a href="home" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Tienda</a>
{% endblock %}

{% block content %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">Nombre Categoria</th>
      <th scope="col">Fecha Creación</th>
      <th scope="col">Acciones</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      {% for categoria in Categorias %}
      <td>{{categoria.NombreCat}}</td>
      <td>{{categoria.FechaCreacion}}</td>
      <td>
        <a href="{% url 'productos:editarRegistroC' categoria.id %}" class="btn mb-3">Editar</a>
        <a href="{% url 'productos:eliminarRegistroC' categoria.id %}" class="btn mb-3">Borrar</a>
      </td>
    </tr>
    {% empty %}
    <tr>
      <td>No hay Categoria</td>

    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}

templates/productosCategoria/paginaEspecial.html
{% extends 'base/index.html' %}
{% load staticfiles %}

{% block extracss %}

{% endblock %}

{% block content %}

<divc class ="container">
  <a href="{% url 'productosCategorias:nuevoRegistroC' %}" class="btn mb-3">Nuevo registro</a>

{% include 'informacion/infocategoria.html' %}
</divc>
{% endblock %}

templates/productosCategoria/prebuntaC.html
{% extends 'base/index.html' %}
{% load staticfiles %}

{% block extracss %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
{% endblock %}

{% block content %}

<div class="container">
	<div class="row justify-content-md-center">
		<div class="col-8">
			<h1>¿Esta seguro de eliminar la Categoria?</h1>
			<form method="post">
				{% csrf_token %}
				{{ form.as_p }}

				<button type="submit" class="btn btn-danger btn-lg btn-block">ELIMINAR</button>
				<a class="btn btn-warning btn-lg btn-block" href="{% url 'productos:infocategorias' %}" class="btn mb-3">CANCELAR</a>
			</form>
		</div>
	</div>
</div>

{% endblock %}